- name: install httpd package
  yum:
    name: httpd
    state: present

- name: start httpd service
  systemd:
    name: httpd.service
    state: started
    enabled: True

- name: write various information to webpage
  template:
    dest: /var/www/html/index.html
    src: index.html.j2

- name: add Foo header to httpd responses
  lineinfile:
    dest: /etc/httpd/conf.d/headers.conf
    line: "Header set X-Foo: foobar"
    regex: "Header set X-Foo:"
    create: True
  notify: reload httpd service

- name: add Bar header to httpd responses
  lineinfile:
    dest: /etc/httpd/conf.d/headers.conf
    line: "Header set X-Bar: foobar"
    regex: "Header set X-Bar:"
    create: True
  notify: reload httpd service

- import_tasks: database.yml